ts_encoder:
  d_model: 512
  d_proj: 256
  patch_size: 16
  num_layers: 8
  num_heads: 8
  d_ff_dropout: 0.1
  max_total_tokens: 8192
  num_query_tokens: 1
  use_rope: true
  activation: "gelu"
  num_features: 1

vision_encoder:
  unpatch: true
  MAX_L: 5000
  finetune_type: "ln"
  mask_ratio: 0.0
  mae_base_arch:
    patch_size: 16
    embed_dim: 768
    depth: 12
    num_heads: 12
    decoder_embed_dim: 512
    decoder_depth: 8
    decoder_num_heads: 16
    mlp_ratio: 4.0

vts_module:
  v_attention:
    num_heads: 8
    dropout: 0.1
  alignment:
    num_heads: 8
    dropout: 0.1
  moe_router:
    channel_num: 3
    num_tasks: 2
    topk: 3
    task_model: 'complex'

vetime_fusion:
  cl_temperature: 0.1
  pos_emb_v_std: 0.02
